name: Build and Push Docker Image to GitHub Packages

on:
  pull_request:
    types:
      - closed
    branches:
      - main
      - master
      - dev

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout base branch (target branch)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          fetch-depth: 0

      - name: Ensure correct branch is checked out
        run: |
          git checkout ${{ github.base_ref }}
          git pull origin ${{ github.base_ref }}
          echo "Current branch: $(git branch --show-current)"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image tag
        run: |
          BRANCH_NAME=${{ github.base_ref }}
          COMMIT_SHA=$(git rev-parse --short HEAD)
          IMAGE_TAG="ghcr.io/${{ github.repository_owner }}/$BRANCH_NAME:$COMMIT_SHA"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
