name: Build and Push Docker Image to GitHub Packages

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*" # Run when pushing version tags like v1.0.0, v1.2.3

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Ensure we fetch all tags

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract branch name (for non-tagged pushes)
        if: startsWith(github.ref, 'refs/heads/')
        id: extract_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Get latest Git tag (for versioning)
        id: version
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            BRANCH_NAME=$VERSION
          else
            VERSION="latest"
            BRANCH_NAME=${{ env.BRANCH_NAME }}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Convert repository owner to lowercase
        id: lowercase_owner
        run: |
          echo "REPO_OWNER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ env.REPO_OWNER }}/${{ env.BRANCH_NAME }}:${{ env.VERSION }} .

      - name: Push Docker image to GitHub Packages
        run: |
          docker push ghcr.io/${{ env.REPO_OWNER }}/${{ env.BRANCH_NAME }}:${{ env.VERSION }}

      - name: List Docker images
        run: docker images
