name: Build and Push Docker Image to GitHub Packages

on:
  push:
    branches:
      - main    # Trigger on push to 'main'
      - dev  # Trigger on push to 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Step 4: Set image tag based on branch
      - name: Set image tag based on branch
        run: |
          if [ "${GITHUB_REF}" == "refs/heads/main" ]; then
            IMAGE_TAG="ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:main"
          elif [ "${GITHUB_REF}" == "refs/heads/master" ]; then
            IMAGE_TAG="ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:123"
          fi
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t $IMAGE_TAG .

      # Step 6: Push Docker image to GitHub Packages
      - name: Push Docker image to GitHub Packages
        run: |
          docker push $IMAGE_TAG
